runtime: nodejs20
entrypoint: node server.js

env: standard
instance_class: F1

env_variables:
  VITE_SUPABASE_URL: "https://wulitgaolidjyrgrilcj.supabase.co"
  VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1bGl0Z2FvbGlkanlyZ3JpbGNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4ODgxMDksImV4cCI6MjA3NjQ2NDEwOX0.TjKb9t_HjHBUyjksPm_ODtt6y3mHxZ_g5_VeitFbNdM"
