runtime: nodejs20
entrypoint: node server.js

env: standard
instance_class: F1

env_variables:
  VITE_SUPABASE_URL: "https://ytyyebmntkhkujpqxmra.supabase.co"
  VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0eXllYm1udGtoa3VqcHF4bXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4Nzk1MDIsImV4cCI6MjA3NjQ1NTUwMn0.gRQtGGh2zChrw96RUSY6o6P-Vier0VaawfN2MpX9uqE"
